spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
mybatis:
  typeAliasesPackage: com.cyp.Hello.entity
  mapperLocations: classpath:mapper/*xml